Update hex-semantic-sync.yml

diff --git a/.github/workflows/hex-semantic-sync.yml b/.github/workflows/hex-semantic-sync.yml
--- a/.github/workflows/hex-semantic-sync.yml
+++ b/.github/workflows/hex-semantic-sync.yml
@@ -1,35 +1,39 @@
 name: Hex Semantic Model Ingest
-on: # This configures when this workflow will be triggered. This can be further customized to only run when certain files change, etc.
-  pull_request: # Run on every pull request
-  push: # Run on every push to the main branch.
+
+on:
+  pull_request:
+  push:
     branches:
       - main
+
 env:
   TOKEN: ${{ secrets.HEX_SEMANTIC_INGEST_TOKEN }}
-  # The top level directory containing your semantic layer files.
-  # By default this is your entire repository, but you can update this is you only want to zip a specific subdirectory.
   DIRECTORY: .
+
 jobs:
   hex-semantic-model-ingest:
     runs-on: ubuntu-latest
     steps:
-    - name: Verify token
-      run: |
-        if [ -z "$TOKEN" ]; then
-          echo "❌ Error: TOKEN not found. Please make sure the secret referenced in your workflow file exists in your repository."
-          exit 1
-        else
-          echo "Token exists, proceeding..."
-        fi
-    - name: Checkout repository
-      uses: actions/checkout@v4
-    - name: Zip up files
-      run: |
+      - name: Verify token
+        run: |
+          if [ -z "$TOKEN" ]; then
+            echo "❌ Error: TOKEN not found. Please make sure the secret referenced in your workflow file exists in your repository."
+            exit 1
+          else
+            echo "Token exists, proceeding..."
+          fi
+
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Zip up files
+        run: |
           cd $DIRECTORY
           zip -r repo.zip .
-    - name: Ingest Semantic Model
-      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
-      run: |
+
+      - name: Ingest Semantic Model
+        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
+        run: |
           response=$(curl -s -w "%{http_code}" -o response.txt -X POST \
             -F "data=@$DIRECTORY/repo.zip" \
             https://app.hex.tech/api/v1/semantic-models/0195f2b6-396e-7007-8d12-43fd068c1bbb/ingest \
@@ -42,19 +46,20 @@ jobs:
             cat response.txt
             exit 1
           fi
-    - name: Ingest Semantic Model (dry run)
-      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
-      run: |
+
+      - name: Ingest Semantic Model (dry run)
+        if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
+        run: |
           response=$(curl -s -w "%{http_code}" -o response.txt -X POST \
             -F "data=@$DIRECTORY/repo.zip" \
             -F "dryRun=true" \
             https://app.hex.tech/api/v1/semantic-models/0195f2b6-396e-7007-8d12-43fd068c1bbb/ingest \
             -H "Authorization: Bearer $TOKEN")
           if [ "$response" -eq 201 ]; then
-            echo "✅ Successfully ingested semantic model. See below for details:"
+            echo "✅ Successfully ingested semantic model (dry run). See below for details:"
             cat response.txt | jq 'del(.debug)'
           else
-            echo "❌ Something went wrong."
+            echo "❌ Something went wrong (dry run)."
             cat response.txt
             exit 1
           fi
